### PR TITLE
Updates for jsonapi-suite

### PR DESCRIPTION
**Pull request by jkeen**
Addon updates to bring this up to speed with the latest jsonapi-suite updates, specifically the sideloading changes as documented [here](https://jsonapi-suite.github.io/jsonapi_suite/concepts#sideloading)

### CODE REVIEW

**Comment by jkeen** [comment]
Oh whoops, this also includes the change in #10, so we can close that one if ya want.

**Comment by leondmello** [comment]
@jkeen could you rebase this and fix conflicts

**Comment by jkeen** [comment]
@leondmello Yep, done and ready ✅

**Comment by jnaglick** [comment]
hey @jkeen This looks great to me except for one discrepancy with where relationships are being serialized. The new expectation of the jsonapi_compliable gem is that relationships are only nested one level deep. So objects in 'included' specify a 'relationships' attribute rather than serializing the entire relationship tree in an attr of the primary object. You can see this behavior [here](https://github.com/jsonapi-suite/jsonapi_compliable/blob/master/lib/jsonapi_compliable/deserializer.rb#L192-L203). 

I've made the changes for this behavior on top of your commit in [my own fork](https://github.com/jnaglick/ember-data-extensions/commit/4a513e0a35b2422dee3f3200e08f958e0771f5a5), let me know what you think

**Comment by jkeen** [comment]
@jnaglick Good catch, looks great!

**Comment by leondmello** [comment]
Should we close this and make a PR from @jnaglick's fork then ?

**Comment by leondmello** [comment]
Already merged via #12

**Pull request closed without merging**
